### ISSUE TITLE
Mapping plausibility check fails for decimal degree

### ISSUE THREAD

**Issue by jmhuss** [klapo/pyfocs#60]
If decimal degree are used for `x_` and `y_coord` to map locations in the `location_library`, the check for plausibility fails since it misinterprets the values (as meter? `dy` does not match the distance in meter, though), raising an error.
Input from config file:
```
    exmpl:
      long name: exmpl
      loc_type: cold
      x_coord:
      - 11.581928
      - 11.581928
      y_coord:
      - 49.926404
      - 49.926312
      z_coord:
      - -0.1
      - -0.1
      LAF:
      - 73.0314
      - 82.2255
```
Error:
```
ValueError: Mapping problem detected for exmpl. Inferred data spacing is
dx = 0.0
dy = -2.6285714284313145e-06
dz = 0.0
total = 2.6285714284313145e-06
dLAF = [0.2542]
```

Including a flag to disable the check globally might be the easiest fix (if there is not already one that I am not aware of), else checking or asking for coordinate system.
